### ISSUE TITLE
unexpected keyword argument 'allow_extra'

### ISSUE THREAD

**Issue by apchenstu** [TuSimple/mx-maskrcnn#104]
Traceback (most recent call last):
  File "path/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "path/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "path/mx-maskrcnn/rcnn/tools/demo_single_image.py", line 159, in <module>
    main()
  File "path/mx-maskrcnn/rcnn/tools/demo_single_image.py", line 156, in main
    thresh = args.thresh)
  File "path/mx-maskrcnn/rcnn/tools/demo_single_image.py", line 27, in demo_maskrcnn
    mod.init_params(arg_params=arg_params, aux_params=aux_params)
  File "rcnn/core/module.py", line 89, in init_params
    force_init=force_init, allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

**Comment by huangzehao** [comment]
Hi, it seems that you use a low version mxnet.
Please try use our provided mxnet. 
https://github.com/apache/incubator-mxnet/tree/bbf8b3e8838ad6531a38de8087ac6055b92802ca
Thanks.
