### ISSUE TITLE
Need help!!!How to resume the training?

### ISSUE THREAD

**Issue by purple7-7** [TuSimple/mx-maskrcnn#50]
My training was ended with rcnn1-0005.params for someone else killed my  program. Then how to resume training at this checkpoint?

**Comment by Zehaos** [comment]
Hi, @purple7-7 
To resume, please revise 'begin_epoch' and 'resume' args in a specific step of train_alternate_mask_fpn.py.

Be aware of a [bug](https://github.com/TuSimple/mx-maskrcnn/commit/afd4ca333ee4c9f9b39da35fd4d787c2b43da31e) just be fix. Please pull the newest version.

**Comment by ypflll** [comment]
@purple7-7  When I set 'begin_epoch' to 6 or 7, it says:
Traceback (most recent call last):
  File "train_alternate_mask_fpn.py", line 114, in <module>
    main()
  File "train_alternate_mask_fpn.py", line 111, in main
    args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
  File "train_alternate_mask_fpn.py", line 31, in alternate_train
    train_shared=False, lr=rpn_lr, lr_step=rpn_lr_step)
  File "/home/.../mx-maskrcnn/rcnn/tools/train_rpn.py", line 135, in train_rpn
    lr_scheduler = mx.lr_scheduler.MultiFactorScheduler(lr_iters, lr_factor)
  File "/home/.../mxnet/python/mxnet/lr_scheduler.py", line 114, in __init__
    assert isinstance(step, list) and len(step) >= 1
AssertionError

So I can't skip the last three epochs?
