### ISSUE TITLE
when training on my own pictures，show error below

### ISSUE THREAD

**Issue by mapleluo** [TuSimple/mx-maskrcnn#56]
num_images 1962
cityscape_small_train gt roidb loaded from model/res50-fpn/cityscape/alternate/cache/cityscape_small_train_gt_roidb.pkl
append flipped images to roidb
filtered 3924 roidb entries: 3924 -> 0
[]
0
Traceback (most recent call last):
  File "train_alternate_mask_fpn.py", line 115, in <module>
    main()
  File "train_alternate_mask_fpn.py", line 112, in main
    args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
  File "train_alternate_mask_fpn.py", line 31, in alternate_train
    train_shared=False, lr=rpn_lr, lr_step=rpn_lr_step)
  File "/home/zhkj/mx-maskrcnn/rcnn/tools/train_rpn.py", line 54, in train_rpn
    allowed_border=9999)
  File "/home/zhkj/mx-maskrcnn/rcnn/core/loader.py", line 407, in __init__
    self.get_batch()
  File "/home/zhkj/mx-maskrcnn/rcnn/core/loader.py", line 507, in get_batch
    iroidb = [roidb[i] for i in range(islice.start, islice.stop)]
IndexError: list index out of range

how to resolve it？thanks for your answer!!!

**Comment by napolun279** [comment]
@mapleluo 
hello! Rencently I use my own dataset, I have encountered the same problem as yours，have you solved this problem？please help me! 
thanks in advance!

**Comment by VasilisGks** [comment]
@mapleluo  @Zehaos  I have the same issue. Any idea of what is going on?

**Comment by dingfg** [comment]
I have the same issue. Any idea of what is going on?

**Comment by xqpinitial** [comment]
@dingfg , I have the same issue. Any idea of what is going on?
