### ISSUE TITLE
The error when training

### ISSUE THREAD

**Issue by chengshuai** [TuSimple/mx-maskrcnn#62]
When run bash scripts/train_alternate.sh, the error occur:

Traceback (most recent call last):
  File "train_alternate_mask_fpn.py", line 114, in <module>
    main()
  File "train_alternate_mask_fpn.py", line 111, in main
    args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
  File "train_alternate_mask_fpn.py", line 31, in alternate_train
    train_shared=False, lr=rpn_lr, lr_step=rpn_lr_step)
  File "/home/chengshuai/mx-maskrcnn-master/rcnn/tools/train_rpn.py", line 148, in train_rpn
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/base_module.py", line 517, in fit
    self.set_params(arg_params, aux_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/base_module.py", line 652, in set_params
    allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

**Comment by huangzehao** [comment]
Hi, did you use the lastest mx-maskrcnn?

**Comment by chengshuai** [comment]
Hi @huangzehao 

The problem is solved by using the lastest mx-maskrcnn.
