### ISSUE TITLE
test my trained model

### ISSUE THREAD

**Issue by mapleluo** [TuSimple/mx-maskrcnn#75]
hi, i follow the steps and train the data and get the trained model. it is 109.9MB, but the download model is 318MB. i use my trained model which is 109.9MB to test image, but it failed. the error is

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gpu-101/mx-maskrcnn/rcnn/tools/demo_single_image.py", line 159, in <module>
    main()
  File "/home/gpu-101/mx-maskrcnn/rcnn/tools/demo_single_image.py", line 156, in main
    thresh = args.thresh)
  File "/home/gpu-101/mx-maskrcnn/rcnn/tools/demo_single_image.py", line 27, in demo_maskrcnn
    mod.init_params(arg_params=arg_params, aux_params=aux_params)
  File "rcnn/core/module.py", line 89, in init_params
    force_init=force_init, allow_extra=allow_extra)
  File "/home/gpu-101/mx-maskrcnn/incubator-mxnet/python/mxnet/module/module.py", line 296, in init_params
    _impl(desc, arr, arg_params)
  File "/home/gpu-101/mx-maskrcnn/incubator-mxnet/python/mxnet/module/module.py", line 287, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: rcnn_fc7_weight is not presented

anyone can help me, thanks!

**Comment by jwnsu** [comment]
what's your model prefix name? The final model file has prefix "final". Any other names (e.g. rpn1/rcnn1) are intermediate files and cannot be used for test or demo.

**Comment by mapleluo** [comment]
@jwnsu  
thanks.i see

**Comment by perp** [comment]
@jwnsu when will combine these intermediate files to final params?
