### ISSUE TITLE
How do I reduce the number of iterations

### ISSUE THREAD

**Issue by mapleluo** [TuSimple/mx-maskrcnn#77]
when i go to the step "TRAIN RCNN WITH IMAGENET INIT AND RPN DETECTION'" use train_maskrcnn, malloc error happened sometimes. so i want to reduce the number of iterations, but how.  any helps, thanks.

**Comment by Zehaos** [comment]
Hi, @mapleluo 
Could you provide more detail about the _malloc error_ ? What type of gpu you used?

**Comment by mapleluo** [comment]
hi ,@Zehaos ,i use 1080ti ，The CPU memory is 11GB.
the error shows below:
Traceback (most recent call last):
  File "train_alternate_mask_fpn.py", line 116, in <module>
    main()
  File "train_alternate_mask_fpn.py", line 113, in main
    args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
  File "train_alternate_mask_fpn.py", line 39, in alternate_train
    vis=False, shuffle=False, thresh=0)
  File "/home/jiawenhe/workspace/mx-maskrcnn/rcnn/tools/test_rpn.py", line 60, in test_rpn
    arg_params=arg_params, aux_params=aux_params)
  File "/home/jiawenhe/workspace/mx-maskrcnn/rcnn/core/tester.py", line 22, in __init__
    self._mod.bind(provide_data, provide_label, for_training=False)
  File "/home/jiawenhe/workspace/mx-maskrcnn/rcnn/core/module.py", line 141, in bind
    force_rebind=False, shared_module=None)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/module.py", line 417, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/executor_group.py", line 231, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/executor_group.py", line 327, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/executor_group.py", line 603, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/symbol/symbol.py", line 1491, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 1024, 2048)
im_info: (1, 3L)
 src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory

**Comment by mapleluo** [comment]
hi ,@Zehaos ,i use 1080ti ，The CPU memory is 11GB.
the error shows below:
Traceback (most recent call last):
File "train_alternate_mask_fpn.py", line 116, in
main()
File "train_alternate_mask_fpn.py", line 113, in main
args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
File "train_alternate_mask_fpn.py", line 39, in alternate_train
vis=False, shuffle=False, thresh=0)
File "/home/jiawenhe/workspace/mx-maskrcnn/rcnn/tools/test_rpn.py", line 60, in test_rpn
arg_params=arg_params, aux_params=aux_params)
File "/home/jiawenhe/workspace/mx-maskrcnn/rcnn/core/tester.py", line 22, in init
self._mod.bind(provide_data, provide_label, for_training=False)
File "/home/jiawenhe/workspace/mx-maskrcnn/rcnn/core/module.py", line 141, in bind
force_rebind=False, shared_module=None)
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/module.py", line 417, in bind
state_names=self._state_names)
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/executor_group.py", line 231, in init
self.bind_exec(data_shapes, label_shapes, shared_group)
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/executor_group.py", line 327, in bind_exec
shared_group))
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/module/executor_group.py", line 603, in _bind_ith_exec
shared_buffer=shared_data_arrays, **input_shapes)
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.12.0-py2.7.egg/mxnet/symbol/symbol.py", line 1491, in simple_bind
raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 1024, 2048)
im_info: (1, 3L)
src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory


 This error may appear when train maskrcnn sometimes.the bache[ ] may be any value.

thanks for your answer

**Comment by hlthu** [comment]
I also meet this error, and the GPU I use is Tesla K20, and the memory is 5.5GB.
Have anyone fixed this problem? Is it just because of the small memory?
But @mapleluo 's 11GB is good enough
