### ISSUE TITLE
when I get to the step "Kick off training"，there are some errors!!!

### ISSUE THREAD

**Issue by napolun279** [TuSimple/mx-maskrcnn#83]
# **# I'm new in deep learning!! I really need your help now. Thanks in advance!**
**when I get to the step "Kick off training",I  run this instruction bash scripts/train_alternate.sh in Command Line, there are some errors like this:**
cling@cling:~/yqj/mx-maskrcnn$ bash scripts/train_alternate.sh 
Traceback (most recent call last):
  File "train_alternate_mask_fpn.py", line 4, in <module>
    import mxnet as mx
  File "/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/__init__.py", line 25, in <module>
    from .base import MXNetError
  File "/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/base.py", line 111, in <module>
    _LIB = _load_lib()
  File "/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/base.py", line 102, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/libinfo.py", line 59, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/libmxnet.so
/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/../../lib/libmxnet.so
/home/cling/yqj/mx-maskrcnn/incubator-mxnet/python/mxnet/../../build/Release/libmxnet.so
/usr/local/cuda-8.0/lib64/libmxnet.so
/usr/local/cuda-8.0/lib64/libmxnet.so
libmxnet.so
../../../libmxnet.so
# and if I run train_alternate_mask_fpn.py in my Pycharm, it comes:
[18:26:19] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [18:26:19] src/ndarray/ndarray.cc:1044: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /home/cling/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x26ab7c) [0x7fb9c035cb7c]
[bt] (1) /home/cling/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2286df0) [0x7fb9c2378df0]
[bt] (2) /home/cling/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(MXNDArrayLoad+0x248) [0x7fb9c21630d8]
[bt] (3) /home/cling/anaconda2/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fba08be3ec0]
[bt] (4) /home/cling/anaconda2/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fba08be387d]
[bt] (5) /home/cling/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x4d6) [0x7fba08df9736]
[bt] (6) /home/cling/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(+0x8a61) [0x7fba08defa61]
[bt] (7) /home/cling/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fba0dd46773]
[bt] (8) /home/cling/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x190b) [0x7fba0ddda53b]
[bt] (9) /home/cling/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9) [0x7fba0dde24e9]

Traceback (most recent call last):
  File "/home/cling/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/cling/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/cling/yqj/mx-maskrcnn/train_alternate_mask_fpn.py", line 114, in <module>
    main()
  File "/home/cling/yqj/mx-maskrcnn/train_alternate_mask_fpn.py", line 111, in main
    args.rcnn_epoch, args.rcnn_lr, args.rcnn_lr_step)
  File "/home/cling/yqj/mx-maskrcnn/train_alternate_mask_fpn.py", line 31, in alternate_train
    train_shared=False, lr=rpn_lr, lr_step=rpn_lr_step)
  File "/home/cling/yqj/mx-maskrcnn/rcnn/tools/train_rpn.py", line 74, in train_rpn
    arg_params, aux_params = load_param(pretrained, epoch, convert=True)
  File "/home/cling/yqj/mx-maskrcnn/rcnn/utils/load_model.py", line 49, in load_param
    arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "/home/cling/yqj/mx-maskrcnn/rcnn/utils/load_model.py", line 15, in load_checkpoint
    save_dict = mx.nd.load('%s-%04d.params' % (prefix, epoch))
  File "/home/cling/anaconda2/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 174, in load
    ctypes.byref(names)))
  File "/home/cling/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:26:19] src/ndarray/ndarray.cc:1044: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /home/cling/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x26ab7c) [0x7fb9c035cb7c]
[bt] (1) /home/cling/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2286df0) [0x7fb9c2378df0]
[bt] (2) /home/cling/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(MXNDArrayLoad+0x248) [0x7fb9c21630d8]
[bt] (3) /home/cling/anaconda2/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fba08be3ec0]
[bt] (4) /home/cling/anaconda2/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fba08be387d]
[bt] (5) /home/cling/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x4d6) [0x7fba08df9736]
[bt] (6) /home/cling/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(+0x8a61) [0x7fba08defa61]
[bt] (7) /home/cling/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fba0dd46773]
[bt] (8) /home/cling/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x190b) [0x7fba0ddda53b]
[bt] (9) /home/cling/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9) [0x7fba0dde24e9]
I want to know if mxnet is not installed sucessfully...
# any helps!thanks!

**Comment by huangzehao** [comment]
It seems that you didn't install mxnet successfully. 
Please refer http://mxnet.incubator.apache.org/install/index.html to re-install mxnet.

**Comment by napolun279** [comment]
yeah, thank you!! I have re-installed mxnet and now the code can run correctly！
